# Generated by Django 3.2 on 2021-04-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0002_auto_20210428_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='quantity_produced',
            field=models.IntegerField(null=True),
        ),
    ]
