# Generated by Django 3.2 on 2021-05-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0003_alter_blueprint_quantity_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='invention',
            name='run_per_success',
            field=models.IntegerField(default=1),
        ),
    ]
