# Generated by Django 3.2 on 2021-05-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0004_invention_run_per_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='cost_prod',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='day_gain',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
