# Generated by Django 3.2 on 2021-05-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0005_auto_20210515_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='month_quantity',
            new_name='week1_quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='month_value',
            new_name='week1_value',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='week_quantity',
            new_name='week2_quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='week_value',
            new_name='week2_value',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='evolution',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week3_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week3_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week4_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week4_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week5_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week5_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week6_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week6_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week7_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week7_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week8_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week8_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
