# Generated by Django 3.2 on 2021-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0006_auto_20210516_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='time_prod',
            field=models.IntegerField(default=3600),
        ),
    ]
