# Generated by Django 3.2 on 2021-05-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0007_blueprint_time_prod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='week2_value',
            new_name='month0_value',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='week3_value',
            new_name='month1_value',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='week1_quantity',
            new_name='month_quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='week4_value',
            new_name='week0_value',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='week2_quantity',
            new_name='week_quantity',
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='cost_prod',
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='day_gain',
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='evolution',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week3_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week4_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week5_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week5_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week6_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week6_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week7_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week7_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week8_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='week8_value',
        ),
    ]
