# Generated by Django 3.2 on 2021-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0008_auto_20210517_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='month_quantity',
            new_name='month0_quantity',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='week_quantity',
            new_name='month1_quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='week0_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='week1_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
