# Generated by Django 3.2 on 2021-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0009_auto_20210517_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='month0_quantity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='month1_quantity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='week0_quantity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='week1_quantity',
            field=models.BigIntegerField(null=True),
        ),
    ]
