# Generated by Django 3.2 on 2021-05-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0010_auto_20210517_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='reaction',
            field=models.BooleanField(default=False),
        ),
    ]
